name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from tag
        id: tag_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Generate changelog
        id: changelog
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -z "$PREVIOUS_TAG" ]; then
            CHANGELOG=$(git log --pretty=format:"* %s (%h)" HEAD)
          else
            CHANGELOG=$(git log --pretty=format:"* %s (%h)" ${PREVIOUS_TAG}..HEAD)
          fi
          echo "CHANGELOG<<CHANGELOG_EOF" >> "$GITHUB_OUTPUT"
          echo "$CHANGELOG" >> "$GITHUB_OUTPUT"
          echo "CHANGELOG_EOF" >> "$GITHUB_OUTPUT"

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: '.'
          severity: error

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Docker Container Management ${{ steps.tag_version.outputs.VERSION }}
          body: |
            # Docker Container Management ${{ steps.tag_version.outputs.VERSION }}

            ## Changes in this Release
            ${{ steps.changelog.outputs.CHANGELOG }}

            ## Features
            - Safe Docker container shutdown with proper cleanup
            - Automatic container startup on system boot
            - Detailed logging system
            - Error handling and recovery
            - GitHub Actions CI integration

            ## Installation
            ```bash
            git clone https://github.com/PeterVinter/Manage_linux_docker_containers.git
            cd Manage_linux_docker_containers
            chmod +x *.sh
            ```

            ## Requirements
            - Docker installed and running
            - Linux operating system
            - Root or sudo privileges
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
