name: Update Changelog

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  update-changelog:
    if: |
      github.event.pull_request.merged == true && 
      !startsWith(github.event.pull_request.title, 'docs: update changelog for v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.PAT_TOKEN }}
          
      - name: Get PR title and body
        id: pr-info
        run: |
          echo "title=${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "${{ github.event.pull_request.body }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Check if only changelog was modified
        id: changelog-check
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          if [ "$CHANGED_FILES" = "CHANGELOG.md" ]; then
            echo "only_changelog=true" >> $GITHUB_OUTPUT
          else
            echo "only_changelog=false" >> $GITHUB_OUTPUT
          fi

      - name: Update Changelog
        if: steps.changelog-check.outputs.only_changelog != 'true'
        run: |
          # Check if CHANGELOG.md exists
          if [ ! -f CHANGELOG.md ]; then
            echo "Error: CHANGELOG.md not found"
            echo "Creating initial CHANGELOG.md"
            echo "# Changelog\n\nAll notable changes to this project will be documented in this file.\n\n" > CHANGELOG.md
            CURRENT_VERSION="0.0.0"
          else
            echo "Reading current version from CHANGELOG.md"
            # Read current version from latest entry with error handling
            CURRENT_VERSION=$(grep -m 1 "## \[v" CHANGELOG.md | sed 's/## \[v\(.*\)\].*/\1/')
            if [ -z "$CURRENT_VERSION" ]; then
              echo "Warning: No version found in CHANGELOG.md, using 0.0.0"
              CURRENT_VERSION="0.0.0"
            else
              echo "Current version: $CURRENT_VERSION"
            fi
          fi
          
          # Get today's date
          DATE=$(date +%Y-%m-%d)
          echo "Generating changelog entry for date: $DATE"
          
          # Increment version based on PR title
          IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
          PR_TITLE="${{ steps.pr-info.outputs.title }}"
          echo "Processing PR title: $PR_TITLE"
          
          if [[ "$PR_TITLE" == *"!"* || "$PR_TITLE" == *"BREAKING CHANGE"* ]]; then
            echo "Detected breaking change, incrementing major version"
            NEW_VERSION="$((major + 1)).0.0"
          elif [[ "$PR_TITLE" == *"feat:"* || "$PR_TITLE" == *"feature:"* ]]; then
            echo "Detected new feature, incrementing minor version"
            NEW_VERSION="${major}.$((minor + 1)).0"
          else
            echo "Detected patch change, incrementing patch version"
            NEW_VERSION="${major}.${minor}.$((patch + 1))"
          fi
          
          echo "New version will be: $NEW_VERSION"
          
          # Create new changelog entry
          NEW_ENTRY="## [v${NEW_VERSION}] - ${DATE}\n\n"
          
          # Determine change type from PR title
          if [[ "$PR_TITLE" == *"!"* || "$PR_TITLE" == *"BREAKING CHANGE"* ]]; then
            CHANGE_TYPE="Breaking Change"
          elif [[ "$PR_TITLE" == *"feat:"* || "$PR_TITLE" == *"feature:"* ]]; then
            CHANGE_TYPE="Added"
          elif [[ "$PR_TITLE" == *"fix:"* ]]; then
            CHANGE_TYPE="Fixed"
          elif [[ "$PR_TITLE" == *"docs:"* ]]; then
            CHANGE_TYPE="Documentation"
          elif [[ "$PR_TITLE" == *"refactor:"* ]]; then
            CHANGE_TYPE="Changed"
          elif [[ "$PR_TITLE" == *"security:"* ]]; then
            CHANGE_TYPE="Security"
          else
            CHANGE_TYPE="Changed"
          fi
          
          echo "Change type determined as: $CHANGE_TYPE"
          NEW_ENTRY+="### ${CHANGE_TYPE}\n"
          NEW_ENTRY+="- ${PR_TITLE#*: }\n"
          
          # Add PR body details if they exist
          if [ ! -z "${{ steps.pr-info.outputs.body }}" ]; then
            echo "Processing PR body for additional details"
            while IFS= read -r line; do
              # Skip PR template checkboxes and empty lines
              if [[ ! "$line" =~ ^\s*-\s*\[[ xX]\] ]]; then
                if [ ! -z "$line" ]; then
                  NEW_ENTRY+="  - $line\n"
                fi
              fi
            done <<< "${{ steps.pr-info.outputs.body }}"
          fi
          
          # Add version link
          NEW_ENTRY+="\n[v${NEW_VERSION}]: https://github.com/PeterVinter/Manage_linux_docker_containers/releases/tag/v${NEW_VERSION}\n"
          
          # Create temporary file with new content
          echo -e "# Changelog\n\nAll notable changes to this project will be documented in this file.\n\nThe format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),\nand this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n\n${NEW_ENTRY}\n$(tail -n +7 CHANGELOG.md)" > CHANGELOG.md.new
          mv CHANGELOG.md.new CHANGELOG.md
          
          # Configure Git
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Create branch and commit changes
          BRANCH_NAME="bot/update-changelog-v${NEW_VERSION}"
          git checkout -b "$BRANCH_NAME"
          git add CHANGELOG.md
          git commit -m "docs: update changelog for v${NEW_VERSION}"
          git push origin "$BRANCH_NAME"
          
          # Create PR
          gh pr create \
            --title "docs: update changelog for v${NEW_VERSION}" \
            --body "Automated changelog update for version ${NEW_VERSION}" \
            --base main \
            --head "$BRANCH_NAME" || {
              echo "Failed to create PR, but continuing..."
            }
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
